# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

stages:
 - stage: Build
   displayName: Build Total Serve client Applications
   jobs:
     - job: BuildApp
       displayName: Build Applications
       steps:
        - task: NodeTool@0
          displayName: Install Node js
          inputs:
            versionSource: 'spec'
            versionSpec: '18.x'
        
        - script: npm install 
          displayName: To restore the Node module to Total serve App
       
        - script: npm run build
          displayName: Build TotalServe App
        
        - task: PublishBuildArtifacts@1
          inputs:
           pathtoPublish: dist
           ArtifactName: 'dist'