# So excited to write my first pipeline

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: Total Serve Client Application

  jobs:
  - job: BuildJob
    displayName: Build Job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: Set up Node.js

    - script: npm install
      displayName: Restore Packages

    - script: npm run build
      displayName: Build Total Serve Application

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'drop'
<<<<<<< HEAD
        PublishLocation: 'dist'
=======
        publishLocation: 'dist'
>>>>>>> eef4284498b88d13765e1c6629bf899848e8462f
