# Welcome to progress CI and CD pipeline

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: esafety App
  jobs:
  - job: BuildApp
    displayName: Build Esafety Application
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: Set up Node.js

    - script: npm install
      displayName: Restore Packages

    - script: npm run build
      displayName: Build Esafety Application

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'drop'

- stage: Deploy
  displayName: Deployment
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployToCloud
    displayName: Deploy to Cloud
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: Download Artifacts
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(Build.ArtifactStagingDirectory)'

    - task: AzureRmWebAppDeployment@4
      displayName: Deploy Azure App Service
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(dc464143-d774-480b-a67f-0d88f5a64406)'
        appType: 'webApp'
        WebAppName: 'esafetyApp'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/drop'
