# Welcome to progress CI and CD pipeline

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: esafety App
  jobs:
  - job: BuildApp
    displayName: Build Esafety Application
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: Set up Node.js

    - script: npm install
      displayName: Restore Packages

    - script: npm run build
      displayName: Build Esafety Application

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'drop'

  - job: ArmTemplate
    displayName: ARM Template for Taylorfield App
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'DevOps/Taylor.json'
        ArtifactName: 'arm'

- stage: Deploy
  displayName: Deployment
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: DeployArm
    displayName: Deploy ARM Template for Taylor
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: Download ARM Template Artifact
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'arm'
        downloadPath: '$(Build.ArtifactStagingDirectory)/drop'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy ARM Template
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure subscription 1(dc464143-d774-480b-a67f-0d88f5a64406)'
        subscriptionId: 'dc464143-d774-480b-a67f-0d88f5a64406'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'Prodevrg'
        location: 'UK West'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.ArtifactStagingDirectory)/drop/DevOps/Taylor.json'
        overrideParameters: '-TtechName "TtechservicePlan" -TtechSKU "Free" -TtechWorkerSize "2"'
        deploymentMode: 'Incremental'
        deploymentName: 'Arm Template Deployment'

  - job: DeployToCloud
    displayName: Deploy to Cloud
    dependsOn: DeployArm
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: Download Artifacts
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(Build.ArtifactStagingDirectory)'

    - task: AzureRmWebAppDeployment@4
      displayName: Deploy Azure App Service
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(dc464143-d774-480b-a67f-0d88f5a64406)'
        appType: 'webApp'
        WebAppName: 'esafetyApp'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/drop'
